### ISSUE TITLE
After running rails new and nuxt new, everything in the console is absolutely fine, no errors. But the files are 100% unchanged

### ISSUE THREAD

**Issue by rrdirnens** [zacharyw/nuxt-rails-docker-boilerplate#1]

**Comment by zacharyw** [comment]
@rrdirnens Are you using Docker for Windows or Docker for Mac?

**Comment by rrdirnens** [comment]
@zacharyw Thank you for the reply. I am using docker toolbox for windows, following these instructions: https://docs.docker.com/toolbox/toolbox_install_windows/. 

It is entirely possible that this is my fault, but I have zero backend experience with Docker, Ruby or RoR, so I can't be certain. I have since attempted to run all the processes again for four times, but to the same result.

**Comment by zacharyw** [comment]
@rrdirnens I can't guarantee this will fix your issue, but Docker Toolbox is an outdated, legacy solution (notice the note at the top of the page, below the header).

Could you try Docker for Windows (https://docs.docker.com/docker-for-windows/) and if that doesn't work, re-comment here and I'll see if I can help.

**Comment by rrdirnens** [comment]
@zacharyw I'm afraid Docker for Windows is not an option at the moment, due to the fact that I have Windows 10 Home, but in order to run Docker you need Window 10 Pro or Enterprise.

**Comment by zacharyw** [comment]
@rrdirnens Hrm, that makes it harder to debug since I don't use Docker Toolbox.

If I had to guess it has something to do with the volume mounts not working correctly, so the files the container tries to generate aren't being created on your local file system.

I found this blog post which gives some debugging tips with volume mounts on windows: https://medium.com/@Charles_Stover/fixing-volumes-in-docker-toolbox-4ad5ace0e572

**Comment by rrdirnens** [comment]
@zacharyw Thank you, I will definitely check the article and see if it can help. I might also avoid docker all together, we'll see how it goes! I really appreciate the help :)
